openapi: 3.0.0
info:
  title: Chat Messenger API
  version: 1.0.0
paths:
  /messages:
    get:
      summary: Get all messages
      operationId: getMessages
      responses:
        "200":
          description: A list of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    message:
                      type: string
                    user:
                      type: string
                    timestamp:
                      type: string
  /message:
    post:
      summary: Send a new message
      operationId: sendMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                user:
                  type: string
      responses:
        "201":
          description: Message created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    type: string
                  timestamp:
                    type: string
                  status:
                    type: string
        "400":
          description: Bad request, invalid input
        "401":
          description: Unauthorized
        "500":
          description: Server error
